checks:
  frequency:
    limit: 5 # Sending this many messages within the interval will count as an offense.
    interval: 100 # The interval in ticks
    commands:
    - "mute %player% 1m spam" # commands to execute when someone passes the limit
  character:
    limit: 3 # max number of repeating characters allowed
    exceptions: # These characters will not be removed for character-spam.
      - '0'
  capital:
    limit: 15 # Maximum number of capital letters in a message
    ignore-links: true # if it looks like a link, should drchat allow it to be
  swear:
    words: # make sure to put the words here in all lowercase.
      - "nigger"
      - "nigga"
      - "faggot"
    commands: # commands to execute if someone uses any one of these words
      - "ban %player% offensive language"

messages:
  no-permission: "&cNo Permission"
  reload: "&6DrChat config reloaded"
  modify-notification:
  - "&7%player%'s message was modified by DrChat."
  - "&7Original message: %original-message%"
  cancel-notification:
  - "&7%player%'s message was cancelled by DrChat."
  - "&7Original message: %original-message%"
  staffchat:
    mc-to-mc-format: "&a&l[Staff] &f%name% &7» &f%message%"
    discord-to-mc-format: "&a&l[Staff] &f%nickname% &9» &f%message%"
    toggle-on: "&6Staffchat is now on"
    toggle-off: "&6Staffchat is now off"
  clear:
    lines: 20
    all: "&6Chat Cleared"
    player: "&6Chat Cleared for %player%"
    invalid-player: "&6Invalid player"
  freeze:
    toggle-on: "&6Chat freeze toggled on"
    toggle-off: "&6Chat freeze toggled off"
    notify: "&4Chat is currently frozen"
  search:
    minecraft: "&6Search results: &cgoogle.com/search?q=%search%"
    discord: "**Search results:** https://google.com/search?q=%search%"

rewards: # requires vault and an economy plugin
  cooldown: 300 # in ticks
  money: 0 # $ per message
  discord:
    all-messages: true # should messages sent in any chat channel be rewarded?
    mc-messages: true # should messages sent in the mc chat channel be rewarded? This setting is ignored if all-messages is set to true

discord: # requires DiscordSRV
  channel-name: "global" # Checks will apply only to this channel
  checks: # Which of these checks should be made when sending the message from Discord to MC
    frequency: true
    font: true
    spacing: true
    capital: true
    character: true
    swear: true
  reactions: # For custom emotes, use the format name:id. Example: "pepe:123123123123"
    modified: "U+2702" # Messages which were sent from Discord and were modified will be reacted with this emote.
    cancelled: "U+274C" # Messages which were sent from Discord and were cancelled will be reacted with this emote
  delete-cancelled: true # Should DrChat delete discord messages that were cancelled
  spam-bypass-role-id: "000000000000000000" # This role will be allowed to bypass all spam checks when sending messages through Discord
  frozen-bypass-role-id: "000000000000000000" # Allowed to talk through a chat freeze
  mute-sync: true # Should DrChat prevent players who are muted in-game from talking in the chat channel. Requires EssentalsX or LiteBans
  mute-role-id: "000000000000000000" # This role will be added to players when they are muted. Requires EssentialsX
  barrier: "» " # Discord -> MC will only filter chat to the right of the first occurrence of this String
  search-role-id: "000000000000000000" # This role will be allowed to search through Discord

search:
  trigger: "?" # this phrase at the beginning of a message will search the rest of the message
  regex: ".*[A-Za-z].*" # the message must match this regex in order for it to be searched.