checks:
  frequency:
    limit: 5 # Sending this many messages within the interval will count as an offense.
    interval: 100 # The interval in ticks
    commands:
    - "mute %player% 1m spam" # commands to execute when someone passes the limit
  character:
    limit: 3
    exceptions: # These characters will not be removed for character-spam.
      - '0'
  capital:
    limit: 15 # Maximum number of capital letters in a message

messages:
  no-permission: "&cNo Permission"
  reload: "&6DrChat config reloaded"
  modify-notification:
  - "&7%player%'s message was modified by DrChat."
  - "&7Original message: %original-message%"
  cancel-notification:
  - "&7%player%'s message was cancelled by DrChat."
  - "&7Original message: %original-message%"
  staffchat:
    mc-to-mc-format: "&a&l[Staff] &f%name% &7» &f%message%"
    discord-to-mc-format: "&a&l[Staff] &f%nickname% &9» &f%message%"

rewards:
  cooldown: 15 #seconds
  money: 1 # $ per message
  discord:
    mc-messages: true
    all-messages: true

discord:
  checks: # Which of these checks should be made when sending the message from Discord to MC
    frequency: true
    font: true
    spacing: true
    capital: true
    character: false
  reactions: # For custom emotes, use the format name:id. Example: "pepe:123123123123"
    modified: "U+2702" # Messages which were sent from Discord and were modified will be reacted with this emote.
    cancelled: "U+274C" # Messages which were sent from Discord and were cancelled will be reacted with this emote
  delete-cancelled: true # Should DrChat delete discord messages that were cancelled
  bypass-role: "Admin" # This role will be allowed to bypass all checks when sending messages through Discord
  mute-sync: true # Should DrChat prevent players who are muted ingame from talking in the chat channel
  barrier: "»" # Discord -> MC will only filter chat to the right of the first occurrence of this String