name: DrChat
version: ${project.version}
main: org.acornmc.drchat.DrChat
api-version: "1.13"
authors: [DrBot]
softdepend: [DiscordSRV, EssentialsX, Vault]
description: Spam Management Tool
commands:
  drchat:
    description: drchat admin commands
    usage: "/<command> reload \n/<command> clear <player> \n/<command> freeze \n<command> broadcast <permission> <message>"
    permission: drchat.command
  staffchat:
    description: drchat's staff chat
    usage: /<command> <message>
    permission: drchat.staffchat
    aliases: [h]
permissions:
  drchat.reload:
    default: false
    description: reload command
    children:
      drchat.command: true
  drchat.freeze:
    default: false
    description: freeze command
    children:
      drchat.command: true
  drchat.clear:
    default: false
    description: clear command
    children:
      drchat.command: true
  drchat.broadcast:
    default: false
    description: broadcast command
    children:
      drchat.command: true
  drchat.bypass.character:
    default: false
    description: bypass character spam
  drchat.bypass.swear:
    default: false
    description: bypass swear spam
  drchat.bypass.capital:
    default: false
    description: bypass capital spam
  drchat.bypass.spacing:
    default: false
    description: bypass spacing spam
  drchat.bypass.font:
    default: false
    description: bypass font spam
  drchat.bypass.frequency:
    default: false
    description: bypass frequency spam
  drchat.bypass.freeze:
    default: false
    description: talk while chat is frozen
  drchat.notify.cancel:
    default: false
    description: notify for cancelled messages
  drchat.notify.modify:
    default: false
    description: notify for modified messages
  drchat.staffchat:
    default: false
    description: use staffchat
  drchat.search:
    default: false
    description: allow for search
  drchat.replace:
    default: false
    description: allows for word replacement