name: DrChat
version: ${project.version}
main: org.acornmc.drchat.DrChat
api-version: "1.13"
authors: [DrBot]
softdepend: [DiscordSRV, EssentialsX]
description: Spam Management Tool
commands:
  drchat:
    description: drchat reload command
    usage: /<command> reload
    permission: drchat.reload
  staffchat:
    description: drchat's staff chat
    usage: /<command> <message>
    permission: drchat.staffchat
    aliases: [h]